export const ACTIVITY_CARD_REQUEST = 'ACTIVITY_CARD_REQUEST'
export const ACTIVITY_CARD_FAILURE = 'FETCH_ACTIVITY_CARD_FAILURE'

export const FETCH_ACTIVITY_CARD_SUCCESS = 'FETCH_ACTIVITY_CARD_SUCCESS'
export const FETCH_ACTIVITY_CARDS_SUCCESS = 'FETCH_ACTIVITY_CARDS_SUCCESS'
export const LIKE_ACTIVITY_CARD_SUCCESS = 'LIKE_FETCH_ACTIVITY_CARD_SUCCESS'
export const DELETE_ACTIVITY_CARD_SUCCESS = 'DELETE_ACTIVITY_CARD_SUCCESS'
export const UPDATE_ACTIVITY_CARD_SUCCESS = 'UPDATE_ACTIVITY_CARD_SUCCESS'
export const CREATE_ACTIVITY_CARD_SUCCESS = 'CREATE_ACTIVITY_CARD_SUCCESS'

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'

export const LOGOUT_REQUEST = 'AUTH_FAILURE'
export const LOGOUT_SUCCESS = 'AUTH_FAILURE'
export const LOGOUT_FAILURE = 'AUTH_FAILURE'

export const USER_ROLE_REQUEST = 'USER_ROLE_REQUEST'
export const USER_ROLE_SUCCESS = 'USER_ROLE_SUCCESS'
export const USER_ROLE_FAILURE = 'USER_ROLE_FAILURE'